---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
data:
  application.conf.in: |
    ktor {
      deployment {
        environment = production
        port = 8080
      }
      application {
        modules = [
          org.ompldr.server.RestApi.main
        ]
      }
    }
    ompldr {
      redirectToHttps = true
      database {
        url = {
          writer = "jdbc:mysql://google/ompldr?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=ompldr:us-east4:ompmaster-mysql4"
          reader = "jdbc:mysql://google/ompldr?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=ompldr:us-east4:ompmaster-mysql4-replica"
        }
        driver = "com.mysql.jdbc.Driver"
        user = "${DB_USER}"
        password = "${DB_PASSWORD}"
      }
      secrets {
        aes_iv = "${AES_IV}"
        aes_secret = "${AES_SECRET}"
      }
      gce {
        projectId = "ompldr"
        bucketNamePrefix = "ompldr-"
        bucketPrefix = "data/v1"
        storage {
          regions = ["us", "eu", "asia"]
          currentRegion = "us"
        }
      }
      lndrpc {
        cafile = "/ssl-certs/OmpAuth.crt"
        host = "lnd-internal.default"
        port = 10009
        macaroonPath = "/macaroons/admin.macaroon"
      }
      ratelimiter {
        burst = 15
        period = 60
        countLimit = 30
        redis {
          host = "redis-master-internal.default"
          port = 6379
        }
      }
    }
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      volumes:
      - name: api-server-config
        configMap:
          name: api-server-config
      - name: ssl-certs
        secret:
          secretName: ssl-certs
      - name: macaroons
        secret:
          secretName: macaroons
      containers:
      - name: server
        image: us.gcr.io/ompldr/server:latest
        resources:
          requests:
            cpu: "0.25"
            memory: "3Gi"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: DB_PASSWORD
          - name: AES_IV
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: AES_IV
          - name: AES_SECRET
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: AES_SECRET
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        volumeMounts:
        - name: api-server-config
          mountPath: /etc/ompldr-config
          readOnly: true
        - name: ssl-certs
          mountPath: /ssl-certs
          readOnly: true
        - name: macaroons
          mountPath: /macaroons
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
  labels:
    app: api-server
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 8080
    nodePort: 30061
  selector:
    app: api-server
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: api-server
spec:
  maxReplicas: 18
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: api-server
  targetCPUUtilizationPercentage: 20
