---
apiVersion: v1
kind: ConfigMap
metadata:
  name: periodic-service-config
data:
  application.conf.in: |
    ktor {
      deployment {
        environment = production
        port = 8080
      }
      application {
        modules = [
          org.ompldr.server.PeriodicService.main
        ]
      }
    }
    ompldr {
      database {
        url = {
          writer = "jdbc:mysql://google/ompldr?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=ompldr:us-east4:ompmaster-mysql4"
          reader = "jdbc:mysql://google/ompldr?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=ompldr:us-east4:ompmaster-mysql4-replica"
        }
        driver = "com.mysql.jdbc.Driver"
        user = "${DB_USER}"
        password = "${DB_PASSWORD}"
      }
      secrets {
        aes_iv = "${AES_IV}"
        aes_secret = "${AES_SECRET}"
      }
      gce {
        projectId = "ompldr"
        bucketNamePrefix = "ompldr-"
        bucketPrefix = "data/v1"
        storage {
          regions = ["us", "eu", "asia"]
          currentRegion = "us"
        }
      }
      lndrpc {
        cafile = "/ssl-certs/OmpAuth.crt"
        host = "lnd-internal.default"
        port = 10009
        macaroonPath = "/macaroons/admin.macaroon"
      }
    }
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: periodic-service
  labels:
    app: periodic-service
    run: periodic-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: periodic-service
  template:
    metadata:
      labels:
        app: periodic-service
    spec:
      volumes:
      - name: periodic-service-config
        configMap:
          name: periodic-service-config
      - name: ssl-certs
        secret:
          secretName: ssl-certs
      - name: macaroons
        secret:
          secretName: macaroons
      containers:
      - name: server
        image: us.gcr.io/ompldr/server:latest
        resources:
          requests:
            cpu: "0.25"
            memory: "2Gi"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: DB_PASSWORD
          - name: AES_IV
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: AES_IV
          - name: AES_SECRET
            valueFrom:
              secretKeyRef:
                name: ompsecrets
                key: AES_SECRET
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        volumeMounts:
        - mountPath: /etc/ompldr-config
          name: periodic-service-config
          readOnly: true
        - name: ssl-certs
          mountPath: /ssl-certs
          readOnly: true
        - name: macaroons
          mountPath: /macaroons
          readOnly: true
